apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: etcd
  namespace: flux-system
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  targetNamespace: garden
  interval: 1m
  dependsOn:
    - name: configuration
    - name: certificates
  chart:
    spec:
      postRenderers:
        - kustomize:
            patches:
              - target:
                  apiVersion: apps/v1
                  kind: StatefulSet
                  name: etcd
                patch: |
                  spec:
                    template:
                      spec:
                        containers:
                        - name: etcd
                          volumeMounts:
                          - name: etcd
                            mountPath: /var/etcd/data
                        - name: backup-restore
                          volumeMounts:
                          - name: etcd
                            mountPath: /var/etcd/data
                    volumeClaimTemplates:
                    - metadata:
                        name: etcd
                      spec:
                        accessModes:
                        - "ReadWriteOnce"
                        resources:
                          requests:
                            storage: 10Gi
      chart: etcd
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: gardener-community-charts
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: etcd-base-values
      optional: false
    - kind: Secret
      name: etcd-values-0
      optional: true
    - kind: Secret
      name: etcd-values-1
      optional: true
    - kind: Secret
      name: etcd-values-2
      optional: true
    - kind: Secret
      name: etcd-values
      optional: true
    # All of below maps cert-manager secrets to the expected helm values
    - kind: Secret
      name: gardener-ca-keypair
      valuesKey: tls.crt
      targetPath: tls.ca.crt
    - kind: Secret
      name: gardener-ca-keypair
      valuesKey: tls.key
      targetPath: tls.ca.key
    - kind: Secret
      name: etcd-tls
      valuesKey: tls.crt
      targetPath: tls.server.crt
    - kind: Secret
      name: etcd-tls
      valuesKey: tls.key
      targetPath: tls.server.key
    - kind: Secret
      name: etcd-client-tls
      valuesKey: tls.crt
      targetPath: tls.client.crt
    - kind: Secret
      name: etcd-client-tls
      valuesKey: tls.key
      targetPath: tls.client.key
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: StatefulSet
            apiVersion: apps/v1
            metadata:
              name: etcd
              namespace: garden
            spec:
              template:
                spec:
                  priorityClassName: gardener-kubernetes
