apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: etcd
  namespace: flux-system
spec:
  install:
    remediation:
      retries: 3
    createNamespace: true
  targetNamespace: garden
  interval: 1m
  dependsOn:
    - name: configuration
    - name: certificates
  chart:
    spec:
      chart: ./helmcharts/etcd
      sourceRef:
        kind: GitRepository
        name: yake
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: Secret
      name: etcd-base-values
      optional: false
    - kind: Secret
      name: etcd-values-0
      optional: true
    - kind: Secret
      name: etcd-values-1
      optional: true
    - kind: Secret
      name: etcd-values-2
      optional: true
    - kind: Secret
      name: etcd-values
      optional: true
    # All of below maps cert-manager secrets to the expected helm values
    - kind: Secret
      name: gardener-ca-keypair
      valuesKey: tls.crt
      targetPath: tls.ca.crt
    - kind: Secret
      name: gardener-ca-keypair
      valuesKey: tls.key
      targetPath: tls.ca.key
    - kind: Secret
      name: etcd-tls
      valuesKey: tls.crt
      targetPath: tls.server.crt
    - kind: Secret
      name: etcd-tls
      valuesKey: tls.key
      targetPath: tls.server.key
    - kind: Secret
      name: etcd-client-tls
      valuesKey: tls.crt
      targetPath: tls.client.crt
    - kind: Secret
      name: etcd-client-tls
      valuesKey: tls.key
      targetPath: tls.client.key
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
              group: apps
              version: v1
              name: etcd
              namespace: garden
            patch: |-
              - op: add
                path: /spec/template/spec/priorityClassName
                value: gardener-kubernetes
              - op: replace
                path: /spec/template/spec/containers/0/volumeMounts/0/name
                value: etcd
              - op: replace
                path: /spec/template/spec/containers/1/volumeMounts/1/name
                value: etcd
              - op: replace
                path: /spec/volumeClaimTemplates/0/metadata/name
                value: etcd
